//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigireadProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int ReviewID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RatingBook { get; set; }
        public string ReviewTextBook { get; set; }
        public Nullable<System.DateTime> ReviewDateBook { get; set; }
        public Nullable<int> RatingWeb { get; set; }
        public string ReviewTextWeb { get; set; }
        public Nullable<System.DateTime> ReviewDateWeb { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Books Books { get; set; }
    }
}
