//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigireadProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaitList
    {
        public int WaitListID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> WaitPosition { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<bool> EmailNotificationSent { get; set; }

        public virtual Users Users { get; set; }
        public virtual Books Books { get; set; }
    }
}
